---
- name: Install Apache Server
  apt:
    name: apache2
    state: present

- name: Install mysql-client
  apt:
    name: mysql-client
    state: present

- name: Install php
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Download Wordpress Archive file
  get_url:
    url: "{{ wordpress_url }}"
    dest: /home/ubuntu

- name: Decompress Archive file
  unarchive:
    src: "/home/ubuntu/{{ wordpress_filename }}"
    remote_src: yes
    dest: /var/www/html/

- name: Copy Database Configure File for Wordpress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: restart apache2
  service:
    name: apache2
    state: restarted
